"""Validation schemas for task requests and responses."""

# These types let us describe calendar dates and timestamps.
from datetime import date, datetime

# BaseModel turns a Python class into a Pydantic validation schema.
# ConfigDict changes how a schema behaves.
# Field lets us add validation rules to individual values.
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
)

class TaskCreate(BaseModel):
    """
    Validate information sent by a client that wants to create a task.

    The client does not choose the ID, completion status, day, or timestamps.
    WeekFlow generates those values on the server.
    """

    # Remove whitespace from the beginning and end of all strings.
    #
    # For example:
    # "  Finish homework  " becomes "Finish homework".
    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    # Every new task must have a title containing at least one character.
    title: str = Field(
        min_length=1,
    )

    # A due date is optional.
    #
    # Pydantic converts an incoming value such as "2026-09-10"
    # into a Python date object.
    due_date: date | None = None

    # Notes are optional, so their value may be a string or None.
    notes: str | None = None

    # WeekFlow supports priorities 0, 1, and 2.
    #
    # If the client leaves priority out, it defaults to 0.
    # ge means "greater than or equal to."
    # le means "less than or equal to."
    priority: int = Field(
        default=0,
        ge=0,
        le=2,
    )

class TaskUpdate(BaseModel):
    """
    Validate changes sent for an existing task.

    Every field can be omitted because PATCH only changes the fields
    included in the request. The route will leave all other fields alone.
    """

    # Clean extra spaces from incoming strings just like TaskCreate does.
    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    # These fields may be omitted from the PATCH request.
    #
    # If title is provided, it must still contain at least one character.
    title: str | None = Field(
        default=None,
        min_length=1,
    )

    # Sending due_date=null moves the task back to Inbox.
    # Leaving due_date out means "do not change its current date."
    due_date: date | None = None

    # Sending notes=null intentionally clears the task's notes.
    notes: str | None = None

    # Priority can be omitted, but a supplied value must remain 0, 1, or 2.
    priority: int | None = Field(
        default=None,
        ge=0,
        le=2,
    )

    # The client may complete or reopen the task.
    completed: bool | None = None

    @field_validator(
        "title",
        "priority",
        "completed",
    )
    @classmethod
    def reject_null_for_required_database_fields(cls, value):
        """
        Allow these fields to be omitted, but not explicitly erased.

        PostgreSQL requires title, priority, and completed to contain values.
        """

        if value is None:
            raise ValueError("value cannot be null")

        return value

class TaskRead(BaseModel):
    """
    Describe the complete task returned by the API.

    It includes both user-provided values and values generated by the server.
    """

    # A SQLAlchemy Task is an object rather than a dictionary.
    #
    # This setting lets Pydantic read attributes such as task.id,
    # task.title, and task.completed from that object.
    model_config = ConfigDict(
        from_attributes=True,
    )

    # PostgreSQL generates the unique ID.
    id: int

    # These values originally came from TaskCreate.
    title: str
    due_date: date | None
    notes: str | None
    priority: int

    # WeekFlow calculates the day from due_date.
    # A task without a due date belongs in Inbox.
    day: str

    # New tasks begin incomplete.
    completed: bool

    # PostgreSQL generates the creation timestamp.
    created_at: datetime

    # This remains None until the task is completed.
    completed_at: datetime | None