"""Validation schemas for task requests and responses."""

# These types let us describe calendar dates and timestamps.
from datetime import date, datetime

# BaseModel turns a Python class into a Pydantic validation schema.
# ConfigDict changes how a schema behaves.
# Field lets us add validation rules to individual values.
from pydantic import BaseModel, ConfigDict, Field


class TaskCreate(BaseModel):
    """
    Validate information sent by a client that wants to create a task.

    The client does not choose the ID, completion status, day, or timestamps.
    WeekFlow generates those values on the server.
    """

    # Remove whitespace from the beginning and end of all strings.
    #
    # For example:
    # "  Finish homework  " becomes "Finish homework".
    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    # Every new task must have a title containing at least one character.
    title: str = Field(
        min_length=1,
    )

    # A due date is optional.
    #
    # Pydantic converts an incoming value such as "2026-09-10"
    # into a Python date object.
    due_date: date | None = None

    # Notes are optional, so their value may be a string or None.
    notes: str | None = None

    # WeekFlow supports priorities 0, 1, and 2.
    #
    # If the client leaves priority out, it defaults to 0.
    # ge means "greater than or equal to."
    # le means "less than or equal to."
    priority: int = Field(
        default=0,
        ge=0,
        le=2,
    )


class TaskRead(BaseModel):
    """
    Describe the complete task returned by the API.

    It includes both user-provided values and values generated by the server.
    """

    # A SQLAlchemy Task is an object rather than a dictionary.
    #
    # This setting lets Pydantic read attributes such as task.id,
    # task.title, and task.completed from that object.
    model_config = ConfigDict(
        from_attributes=True,
    )

    # PostgreSQL generates the unique ID.
    id: int

    # These values originally came from TaskCreate.
    title: str
    due_date: date | None
    notes: str | None
    priority: int

    # WeekFlow calculates the day from due_date.
    # A task without a due date belongs in Inbox.
    day: str

    # New tasks begin incomplete.
    completed: bool

    # PostgreSQL generates the creation timestamp.
    created_at: datetime

    # This remains None until the task is completed.
    completed_at: datetime | None