"""create brain dumps and task templates tables

Revision ID: 2fd043b83410
Revises: 6a20efc9e315
Create Date: 2026-09-23 09:22:01.940473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd043b83410'
down_revision: Union[str, Sequence[str], None] = '6a20efc9e315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_dumps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_brain_dump_id', sa.BigInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(body) <> ''", name='ck_brain_dumps_body_not_blank'),
    sa.CheckConstraint('\n            (\n                archived IS TRUE\n                AND archived_at IS NOT NULL\n            )\n            OR\n            (\n                archived IS FALSE\n                AND archived_at IS NULL\n            )\n            ', name='ck_brain_dumps_archive_pair'),
    sa.CheckConstraint('\n            source_brain_dump_id IS NULL\n            OR source_brain_dump_id > 0\n            ', name='ck_brain_dumps_source_id_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_brain_dump_id', name='uq_brain_dumps_source_brain_dump_id')
    )
    op.create_index('ix_brain_dumps_archived_created_at', 'brain_dumps', ['archived', 'created_at'], unique=False)
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_task_template_id', sa.BigInteger(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(title) <> ''", name='ck_task_templates_title_not_blank'),
    sa.CheckConstraint('\n            source_task_template_id IS NULL\n            OR source_task_template_id > 0\n            ', name='ck_task_templates_source_id_positive'),
    sa.CheckConstraint('priority BETWEEN 0 AND 2', name='ck_task_templates_priority_range'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_task_template_id', name='uq_task_templates_source_task_template_id')
    )
    op.create_index('ix_task_templates_goal_id', 'task_templates', ['goal_id'], unique=False)
    op.create_index('ix_task_templates_updated_at', 'task_templates', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_templates_updated_at', table_name='task_templates')
    op.drop_index('ix_task_templates_goal_id', table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index('ix_brain_dumps_archived_created_at', table_name='brain_dumps')
    op.drop_table('brain_dumps')
    # ### end Alembic commands ###
