"""create weekly review history tables

Revision ID: 48c150ee4c2a
Revises: a62982ceb618
Create Date: 2026-09-22 13:20:30.932542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c150ee4c2a'
down_revision: Union[str, Sequence[str], None] = 'a62982ceb618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_weekly_commitment_id', sa.BigInteger(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(title) <> '' AND char_length(title) <= 180", name='ck_weekly_commitments_title_valid'),
    sa.CheckConstraint('EXTRACT(ISODOW FROM week_start) = 1', name='ck_weekly_commitments_week_starts_monday'),
    sa.CheckConstraint('\n            (\n                completed IS TRUE\n                AND completed_at IS NOT NULL\n            )\n            OR\n            (\n                completed IS FALSE\n                AND completed_at IS NULL\n            )\n            ', name='ck_weekly_commitments_completion_pair'),
    sa.CheckConstraint('\n            source_weekly_commitment_id IS NULL\n            OR source_weekly_commitment_id > 0\n            ', name='ck_weekly_commitments_source_id_positive'),
    sa.ForeignKeyConstraint(['cycle_id'], ['planning_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_weekly_commitment_id', name='uq_weekly_commitments_source_weekly_commitment_id')
    )
    op.create_index('ix_weekly_commitments_cycle_id', 'weekly_commitments', ['cycle_id'], unique=False)
    op.create_index('ix_weekly_commitments_week_start', 'weekly_commitments', ['week_start', 'completed', 'id'], unique=False)
    op.create_index('uq_weekly_commitments_week_task', 'weekly_commitments', ['week_start', 'task_id'], unique=True, postgresql_where=sa.text('task_id IS NOT NULL'))
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_weekly_review_id', sa.BigInteger(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('what_went_well', sa.String(length=2000), nullable=True),
    sa.Column('what_caused_problems', sa.String(length=2000), nullable=True),
    sa.Column('what_learned', sa.String(length=2000), nullable=True),
    sa.Column('what_change_next_week', sa.String(length=2000), nullable=True),
    sa.Column('next_week_focus', sa.String(length=2000), nullable=True),
    sa.Column('snapshot_completed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_unfinished_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_overdue_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_completion_rate', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_goals_progressed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_best_day', sa.String(length=9), nullable=True),
    sa.Column('snapshot_best_day_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_archived_brain_dump_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_high_priority_completed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_recurring_completed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                snapshot_best_day IS NULL\n                AND snapshot_best_day_count = 0\n            )\n            OR\n            (\n                snapshot_best_day IN (\n                    'Monday',\n                    'Tuesday',\n                    'Wednesday',\n                    'Thursday',\n                    'Friday',\n                    'Saturday',\n                    'Sunday'\n                )\n                AND snapshot_best_day_count > 0\n            )\n            ", name='ck_weekly_reviews_best_day_consistent'),
    sa.CheckConstraint('EXTRACT(ISODOW FROM week_start) = 1', name='ck_weekly_reviews_week_starts_monday'),
    sa.CheckConstraint('\n            (what_went_well IS NULL\n                OR char_length(what_went_well) <= 2000)\n            AND\n            (what_caused_problems IS NULL\n                OR char_length(what_caused_problems) <= 2000)\n            AND\n            (what_learned IS NULL\n                OR char_length(what_learned) <= 2000)\n            AND\n            (what_change_next_week IS NULL\n                OR char_length(what_change_next_week) <= 2000)\n            AND\n            (next_week_focus IS NULL\n                OR char_length(next_week_focus) <= 2000)\n            ', name='ck_weekly_reviews_response_lengths'),
    sa.CheckConstraint('\n            snapshot_completed_count >= 0\n            AND snapshot_unfinished_count >= 0\n            AND snapshot_overdue_count >= 0\n            AND snapshot_goals_progressed_count >= 0\n            AND snapshot_best_day_count >= 0\n            AND snapshot_archived_brain_dump_count >= 0\n            AND snapshot_high_priority_completed_count >= 0\n            AND snapshot_recurring_completed_count >= 0\n            ', name='ck_weekly_reviews_snapshot_counts_nonnegative'),
    sa.CheckConstraint('\n            snapshot_completion_rate =\n                CASE\n                    WHEN (\n                        snapshot_completed_count\n                        + snapshot_unfinished_count\n                    ) = 0\n                    THEN 0\n                    ELSE CAST(\n                        ROUND(\n                            (\n                                CAST(\n                                    snapshot_completed_count\n                                    AS numeric\n                                ) * 100\n                            )\n                            / (\n                                snapshot_completed_count\n                                + snapshot_unfinished_count\n                            )\n                        )\n                        AS integer\n                    )\n                END\n            ', name='ck_weekly_reviews_completion_rate_consistent'),
    sa.CheckConstraint('\n            snapshot_goals_progressed_count\n                <= snapshot_completed_count\n            AND snapshot_best_day_count\n                <= snapshot_completed_count\n            AND snapshot_high_priority_completed_count\n                <= snapshot_completed_count\n            AND snapshot_recurring_completed_count\n                <= snapshot_completed_count\n            ', name='ck_weekly_reviews_completed_counts_consistent'),
    sa.CheckConstraint('\n            source_weekly_review_id IS NULL\n            OR source_weekly_review_id > 0\n            ', name='ck_weekly_reviews_source_id_positive'),
    sa.CheckConstraint('snapshot_completion_rate BETWEEN 0 AND 100', name='ck_weekly_reviews_completion_rate_range'),
    sa.CheckConstraint('snapshot_overdue_count <= snapshot_unfinished_count', name='ck_weekly_reviews_overdue_count_consistent'),
    sa.ForeignKeyConstraint(['cycle_id'], ['planning_cycles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_weekly_review_id', name='uq_weekly_reviews_source_weekly_review_id'),
    sa.UniqueConstraint('week_start', name='uq_weekly_reviews_week_start')
    )
    op.create_index('ix_weekly_reviews_cycle_id', 'weekly_reviews', ['cycle_id'], unique=False)
    op.create_table('weekly_task_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_weekly_task_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('task_title', sa.Text(), nullable=False),
    sa.Column('original_due_date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('resolved_due_date', sa.Date(), nullable=True),
    sa.Column('recurring_rule_id', sa.Integer(), nullable=True),
    sa.Column('source_recurring_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('recurrence_occurrence_date', sa.Date(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                action IN ('nextWeek', 'reschedule')\n                AND resolved_due_date IS NOT NULL\n            )\n            OR\n            (\n                action IN ('inbox', 'keep', 'delete')\n                AND resolved_due_date IS NULL\n            )\n            ", name='ck_weekly_task_decisions_resolved_date_action'),
    sa.CheckConstraint("\n            action <> 'nextWeek'\n            OR resolved_due_date = original_due_date + 7\n            ", name='ck_weekly_task_decisions_next_week_date'),
    sa.CheckConstraint("\n            action IN (\n                'nextWeek',\n                'inbox',\n                'reschedule',\n                'keep',\n                'delete'\n            )\n            ", name='ck_weekly_task_decisions_action'),
    sa.CheckConstraint("action <> 'delete' OR task_id IS NULL", name='ck_weekly_task_decisions_deleted_task_unlinked'),
    sa.CheckConstraint("btrim(task_title) <> ''", name='ck_weekly_task_decisions_title_not_blank'),
    sa.CheckConstraint('EXTRACT(ISODOW FROM week_start) = 1', name='ck_weekly_task_decisions_week_starts_monday'),
    sa.CheckConstraint('\n            (\n                recurring_rule_id IS NULL\n                AND source_recurring_rule_id IS NULL\n                AND recurrence_occurrence_date IS NULL\n            )\n            OR\n            (\n                recurrence_occurrence_date IS NOT NULL\n                AND (\n                    recurring_rule_id IS NOT NULL\n                    OR source_recurring_rule_id IS NOT NULL\n                )\n            )\n            ', name='ck_weekly_task_decisions_recurrence_identity'),
    sa.CheckConstraint('\n            original_due_date >= week_start\n            AND original_due_date < week_start + 7\n            ', name='ck_weekly_task_decisions_original_date_in_week'),
    sa.CheckConstraint('\n            recurring_rule_id IS NULL\n            OR recurring_rule_id > 0\n            ', name='ck_weekly_task_decisions_recurring_rule_id_positive'),
    sa.CheckConstraint('\n            source_recurring_rule_id IS NULL\n            OR source_recurring_rule_id > 0\n            ', name='ck_weekly_task_decisions_source_recurring_rule_id_positive'),
    sa.CheckConstraint('\n            source_weekly_task_decision_id IS NULL\n            OR source_weekly_task_decision_id > 0\n            ', name='ck_weekly_task_decisions_source_id_positive'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_weekly_task_decision_id', name='uq_weekly_task_decisions_source_weekly_task_decision_id')
    )
    op.create_index('ix_weekly_task_decisions_week_decided_at', 'weekly_task_decisions', ['week_start', 'decided_at'], unique=False)
    op.create_index('uq_weekly_task_decisions_task_identity', 'weekly_task_decisions', ['week_start', 'task_id', 'original_due_date'], unique=True, postgresql_where=sa.text('task_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_weekly_task_decisions_task_identity', table_name='weekly_task_decisions', postgresql_where=sa.text('task_id IS NOT NULL'))
    op.drop_index('ix_weekly_task_decisions_week_decided_at', table_name='weekly_task_decisions')
    op.drop_table('weekly_task_decisions')
    op.drop_index('ix_weekly_reviews_cycle_id', table_name='weekly_reviews')
    op.drop_table('weekly_reviews')
    op.drop_index('uq_weekly_commitments_week_task', table_name='weekly_commitments', postgresql_where=sa.text('task_id IS NOT NULL'))
    op.drop_index('ix_weekly_commitments_week_start', table_name='weekly_commitments')
    op.drop_index('ix_weekly_commitments_cycle_id', table_name='weekly_commitments')
    op.drop_table('weekly_commitments')
    # ### end Alembic commands ###
