"""protect recurring task import identity

Revision ID: 7b4d009f9be2
Revises: 68c2642f766e
Create Date: 2026-09-18 10:23:10.798881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4d009f9be2'
down_revision: Union[str, Sequence[str], None] = '68c2642f766e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tasks_source_recurring_occurrence', 'tasks', ['source_recurring_rule_id', 'recurrence_occurrence_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tasks_source_recurring_occurrence', 'tasks', type_='unique')
    # ### end Alembic commands ###
