"""create planning cycles table

Revision ID: 846a2089d8c2
Revises: 7b4d009f9be2
Create Date: 2026-09-21 13:11:47.186119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846a2089d8c2'
down_revision: Union[str, Sequence[str], None] = '7b4d009f9be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_planning_cycle_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('primary_focus', sa.String(length=300), nullable=True),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('\n            (\n                active IS TRUE\n                AND completed_at IS NULL\n            )\n            OR\n            (\n                active IS FALSE\n                AND completed_at IS NOT NULL\n            )\n            ', name='ck_planning_cycles_active_completion_pair'),
    sa.CheckConstraint('\n            source_planning_cycle_id IS NULL\n            OR source_planning_cycle_id > 0\n            ', name='ck_planning_cycles_source_id_positive'),
    sa.CheckConstraint('end_date = start_date + 83', name='ck_planning_cycles_twelve_weeks'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_planning_cycle_id', name='uq_planning_cycles_source_planning_cycle_id')
    )
    op.create_index('uq_planning_cycles_single_active', 'planning_cycles', ['active'], unique=True, postgresql_where=sa.text('active IS TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_planning_cycles_single_active', table_name='planning_cycles', postgresql_where=sa.text('active IS TRUE'))
    op.drop_table('planning_cycles')
    # ### end Alembic commands ###
