"""create recurring rules and exceptions tables

Revision ID: a62982ceb618
Revises: dee397847f46
Create Date: 2026-09-21 13:52:30.456917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a62982ceb618'
down_revision: Union[str, Sequence[str], None] = 'dee397847f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_recurring_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('weekdays', postgresql.ARRAY(sa.SmallInteger()), server_default=sa.text("'{}'::smallint[]"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            frequency <> 'certainDays'\n            OR cardinality(weekdays) > 0\n            ", name='ck_recurring_rules_certain_days_weekdays'),
    sa.CheckConstraint("\n            frequency IN (\n                'daily',\n                'weekly',\n                'everyTwoWeeks',\n                'certainDays',\n                'monthly'\n            )\n            ", name='ck_recurring_rules_frequency'),
    sa.CheckConstraint("btrim(title) <> ''", name='ck_recurring_rules_title_not_blank'),
    sa.CheckConstraint('\n            array_position(weekdays, NULL) IS NULL\n            AND weekdays\n                <@ ARRAY[0, 1, 2, 3, 4, 5, 6]::smallint[]\n            ', name='ck_recurring_rules_weekday_values'),
    sa.CheckConstraint('\n            cardinality(weekdays) =\n                (CASE WHEN 0 = ANY(weekdays) THEN 1 ELSE 0 END)\n                + (CASE WHEN 1 = ANY(weekdays) THEN 1 ELSE 0 END)\n                + (CASE WHEN 2 = ANY(weekdays) THEN 1 ELSE 0 END)\n                + (CASE WHEN 3 = ANY(weekdays) THEN 1 ELSE 0 END)\n                + (CASE WHEN 4 = ANY(weekdays) THEN 1 ELSE 0 END)\n                + (CASE WHEN 5 = ANY(weekdays) THEN 1 ELSE 0 END)\n                + (CASE WHEN 6 = ANY(weekdays) THEN 1 ELSE 0 END)\n            ', name='ck_recurring_rules_weekdays_unique'),
    sa.CheckConstraint('\n            end_date IS NULL\n            OR end_date >= start_date\n            ', name='ck_recurring_rules_date_order'),
    sa.CheckConstraint('\n            source_recurring_rule_id IS NULL\n            OR source_recurring_rule_id > 0\n            ', name='ck_recurring_rules_source_id_positive'),
    sa.CheckConstraint('priority BETWEEN 0 AND 2', name='ck_recurring_rules_priority_range'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_recurring_rule_id', name='uq_recurring_rules_source_recurring_rule_id')
    )
    op.create_index('ix_recurring_rules_active', 'recurring_rules', ['active'], unique=False)
    op.create_index('ix_recurring_rules_goal_id', 'recurring_rules', ['goal_id'], unique=False)
    op.create_table('recurring_occurrence_exceptions',
    sa.Column('recurring_rule_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recurring_rule_id'], ['recurring_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recurring_rule_id', 'occurrence_date')
    )
    op.create_index('ix_recurring_occurrence_exceptions_occurrence_date', 'recurring_occurrence_exceptions', ['occurrence_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recurring_occurrence_exceptions_occurrence_date', table_name='recurring_occurrence_exceptions')
    op.drop_table('recurring_occurrence_exceptions')
    op.drop_index('ix_recurring_rules_goal_id', table_name='recurring_rules')
    op.drop_index('ix_recurring_rules_active', table_name='recurring_rules')
    op.drop_table('recurring_rules')
    # ### end Alembic commands ###
