"""create cycle reviews and goal outcomes tables

Revision ID: bb4c84a73202
Revises: 48c150ee4c2a
Create Date: 2026-09-22 13:48:35.952490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb4c84a73202'
down_revision: Union[str, Sequence[str], None] = '48c150ee4c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_cycle_review_id', sa.BigInteger(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('biggest_accomplishment', sa.String(length=2000), nullable=True),
    sa.Column('biggest_challenge', sa.String(length=2000), nullable=True),
    sa.Column('what_worked_well', sa.String(length=2000), nullable=True),
    sa.Column('what_change_next_cycle', sa.String(length=2000), nullable=True),
    sa.Column('what_stop_doing', sa.String(length=2000), nullable=True),
    sa.Column('what_continue_doing', sa.String(length=2000), nullable=True),
    sa.Column('what_learned', sa.String(length=2000), nullable=True),
    sa.Column('snapshot_goal_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_goal_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_task_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_milestone_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_milestone_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_weekly_reviews_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_best_week_number', sa.Integer(), nullable=True),
    sa.Column('snapshot_best_week_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_best_day', sa.Text(), nullable=True),
    sa.Column('snapshot_best_day_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_high_priority_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_recurring_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_rewards_unlocked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_brain_dumps_archived', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_cycle_name', sa.String(length=80), nullable=True),
    sa.Column('next_cycle_primary_focus', sa.String(length=300), nullable=True),
    sa.Column('next_cycle_theme', sa.String(length=120), nullable=True),
    sa.Column('next_cycle_start_date', sa.Date(), nullable=True),
    sa.Column('next_cycle_first_commitments', postgresql.ARRAY(sa.String(length=180)), server_default=sa.text("'{}'::varchar(180)[]"), nullable=False),
    sa.Column('next_cycle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('\n            (biggest_accomplishment IS NULL\n                OR char_length(biggest_accomplishment) <= 2000)\n            AND\n            (biggest_challenge IS NULL\n                OR char_length(biggest_challenge) <= 2000)\n            AND\n            (what_worked_well IS NULL\n                OR char_length(what_worked_well) <= 2000)\n            AND\n            (what_change_next_cycle IS NULL\n                OR char_length(what_change_next_cycle) <= 2000)\n            AND\n            (what_stop_doing IS NULL\n                OR char_length(what_stop_doing) <= 2000)\n            AND\n            (what_continue_doing IS NULL\n                OR char_length(what_continue_doing) <= 2000)\n            AND\n            (what_learned IS NULL\n                OR char_length(what_learned) <= 2000)\n            ', name='ck_cycle_reviews_response_lengths'),
    sa.CheckConstraint('\n            cardinality(next_cycle_first_commitments) <= 5\n            AND array_position(\n                next_cycle_first_commitments,\n                NULL\n            ) IS NULL\n            ', name='ck_cycle_reviews_first_commitments_shape'),
    sa.CheckConstraint('\n            finalized_at IS NULL\n            OR next_cycle_start_date IS NOT NULL\n            ', name='ck_cycle_reviews_finalized_plan'),
    sa.CheckConstraint('\n            snapshot_best_week_number IS NULL\n            OR snapshot_best_week_number BETWEEN 1 AND 12\n            ', name='ck_cycle_reviews_best_week_number'),
    sa.CheckConstraint('\n            snapshot_goal_completed <= snapshot_goal_total\n            AND snapshot_milestone_completed\n                <= snapshot_milestone_total\n            AND snapshot_high_priority_completed\n                <= snapshot_task_completed\n            AND snapshot_recurring_completed\n                <= snapshot_task_completed\n            AND snapshot_rewards_unlocked\n                <= snapshot_goal_completed\n            AND snapshot_best_week_count\n                <= snapshot_task_completed\n            AND snapshot_best_day_count\n                <= snapshot_task_completed\n            ', name='ck_cycle_reviews_snapshot_counts_consistent'),
    sa.CheckConstraint('\n            snapshot_goal_total >= 0\n            AND snapshot_goal_completed >= 0\n            AND snapshot_task_completed >= 0\n            AND snapshot_milestone_total >= 0\n            AND snapshot_milestone_completed >= 0\n            AND snapshot_weekly_reviews_completed >= 0\n            AND snapshot_longest_streak >= 0\n            AND snapshot_best_week_count >= 0\n            AND snapshot_best_day_count >= 0\n            AND snapshot_high_priority_completed >= 0\n            AND snapshot_recurring_completed >= 0\n            AND snapshot_rewards_unlocked >= 0\n            AND snapshot_brain_dumps_archived >= 0\n            ', name='ck_cycle_reviews_snapshot_counts_nonnegative'),
    sa.CheckConstraint('\n            source_cycle_review_id IS NULL\n            OR source_cycle_review_id > 0\n            ', name='ck_cycle_reviews_source_id_positive'),
    sa.ForeignKeyConstraint(['cycle_id'], ['planning_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_cycle_id'], ['planning_cycles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', name='uq_cycle_reviews_cycle_id'),
    sa.UniqueConstraint('source_cycle_review_id', name='uq_cycle_reviews_source_cycle_review_id')
    )
    op.create_index('ix_cycle_reviews_next_cycle_id', 'cycle_reviews', ['next_cycle_id'], unique=False)
    op.create_table('cycle_goal_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_cycle_goal_outcome_id', sa.BigInteger(), nullable=True),
    sa.Column('cycle_review_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('goal_title', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('replacement_title', sa.String(length=180), nullable=True),
    sa.Column('destination_goal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                action = 'replace'\n                AND replacement_title IS NOT NULL\n                AND btrim(replacement_title) <> ''\n            )\n            OR\n            (\n                action <> 'replace'\n                AND replacement_title IS NULL\n            )\n            ", name='ck_cycle_goal_outcomes_replacement_action'),
    sa.CheckConstraint("\n            action IN (\n                'complete',\n                'carryForward',\n                'archive',\n                'replace'\n            )\n            ", name='ck_cycle_goal_outcomes_action'),
    sa.CheckConstraint("btrim(goal_title) <> ''", name='ck_cycle_goal_outcomes_title_not_blank'),
    sa.CheckConstraint('\n            source_cycle_goal_outcome_id IS NULL\n            OR source_cycle_goal_outcome_id > 0\n            ', name='ck_cycle_goal_outcomes_source_id_positive'),
    sa.ForeignKeyConstraint(['cycle_review_id'], ['cycle_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_cycle_goal_outcome_id', name='uq_cycle_goal_outcomes_source_id')
    )
    op.create_index('ix_cycle_goal_outcomes_destination_id', 'cycle_goal_outcomes', ['destination_goal_id'], unique=False)
    op.create_index('ix_cycle_goal_outcomes_review_id', 'cycle_goal_outcomes', ['cycle_review_id', 'id'], unique=False)
    op.create_index('uq_cycle_goal_outcomes_review_goal', 'cycle_goal_outcomes', ['cycle_review_id', 'goal_id'], unique=True, postgresql_where=sa.text('goal_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_cycle_goal_outcomes_review_goal', table_name='cycle_goal_outcomes', postgresql_where=sa.text('goal_id IS NOT NULL'))
    op.drop_index('ix_cycle_goal_outcomes_review_id', table_name='cycle_goal_outcomes')
    op.drop_index('ix_cycle_goal_outcomes_destination_id', table_name='cycle_goal_outcomes')
    op.drop_table('cycle_goal_outcomes')
    op.drop_index('ix_cycle_reviews_next_cycle_id', table_name='cycle_reviews')
    op.drop_table('cycle_reviews')
    # ### end Alembic commands ###
