"""create goals and milestones tables

Revision ID: dee397847f46
Revises: 846a2089d8c2
Create Date: 2026-09-21 13:27:40.617515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee397847f46'
down_revision: Union[str, Sequence[str], None] = '846a2089d8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_goal_id', sa.BigInteger(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reward', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('success_definition', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('completion_what_helped', sa.String(length=1000), nullable=True),
    sa.Column('completion_hardest_part', sa.String(length=1000), nullable=True),
    sa.Column('completion_learned', sa.String(length=1000), nullable=True),
    sa.Column('completion_do_differently', sa.String(length=1000), nullable=True),
    sa.Column('completion_task_total', sa.Integer(), nullable=True),
    sa.Column('completion_task_completed', sa.Integer(), nullable=True),
    sa.Column('completion_milestone_total', sa.Integer(), nullable=True),
    sa.Column('completion_milestone_completed', sa.Integer(), nullable=True),
    sa.Column('completion_high_priority_completed', sa.Integer(), nullable=True),
    sa.CheckConstraint("btrim(title) <> ''", name='ck_goals_title_not_blank'),
    sa.CheckConstraint('\n            (\n                completed IS TRUE\n                AND completed_at IS NOT NULL\n            )\n            OR\n            (\n                completed IS FALSE\n                AND completed_at IS NULL\n            )\n            ', name='ck_goals_completion_pair'),
    sa.CheckConstraint('\n            (\n                completion_task_total IS NULL\n                OR completion_task_total >= 0\n            )\n            AND\n            (\n                completion_task_completed IS NULL\n                OR completion_task_completed >= 0\n            )\n            AND\n            (\n                completion_milestone_total IS NULL\n                OR completion_milestone_total >= 0\n            )\n            AND\n            (\n                completion_milestone_completed IS NULL\n                OR completion_milestone_completed >= 0\n            )\n            AND\n            (\n                completion_high_priority_completed IS NULL\n                OR completion_high_priority_completed >= 0\n            )\n            ', name='ck_goals_completion_counts_nonnegative'),
    sa.CheckConstraint('\n            completion_milestone_total IS NULL\n            OR completion_milestone_completed IS NULL\n            OR completion_milestone_completed\n                <= completion_milestone_total\n            ', name='ck_goals_milestone_snapshot_counts'),
    sa.CheckConstraint('\n            completion_task_completed IS NULL\n            OR completion_high_priority_completed IS NULL\n            OR completion_high_priority_completed\n                <= completion_task_completed\n            ', name='ck_goals_high_priority_snapshot_count'),
    sa.CheckConstraint('\n            completion_task_total IS NULL\n            OR completion_task_completed IS NULL\n            OR completion_task_completed <= completion_task_total\n            ', name='ck_goals_task_snapshot_counts'),
    sa.CheckConstraint('\n            source_goal_id IS NULL\n            OR source_goal_id > 0\n            ', name='ck_goals_source_id_positive'),
    sa.CheckConstraint('end_date >= start_date', name='ck_goals_date_order'),
    sa.ForeignKeyConstraint(['cycle_id'], ['planning_cycles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_goal_id', name='uq_goals_source_goal_id')
    )
    op.create_index('ix_goals_cycle_id', 'goals', ['cycle_id'], unique=False)
    op.create_table('goal_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_goal_milestone_id', sa.BigInteger(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(title) <> ''", name='ck_goal_milestones_title_not_blank'),
    sa.CheckConstraint('\n            (\n                completed IS TRUE\n                AND completed_at IS NOT NULL\n            )\n            OR\n            (\n                completed IS FALSE\n                AND completed_at IS NULL\n            )\n            ', name='ck_goal_milestones_completion_pair'),
    sa.CheckConstraint('\n            source_goal_milestone_id IS NULL\n            OR source_goal_milestone_id > 0\n            ', name='ck_goal_milestones_source_id_positive'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_goal_milestone_id', name='uq_goal_milestones_source_id')
    )
    op.create_index('ix_goal_milestones_goal_id', 'goal_milestones', ['goal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goal_milestones_goal_id', table_name='goal_milestones')
    op.drop_table('goal_milestones')
    op.drop_index('ix_goals_cycle_id', table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
